language: scala
jdk:
- openjdk8
- openjdk11
scala:
- 2.12.8
- 2.13.0
script: bash ci/test_standalone.sh
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
